import type { CommandType } from "./commands";

// Stage 4, S4.7 (L-d): between the Mac's suspend and resume, main holds back the window's commands that START PAID WORK or MOVE A LAUNCH, and lets the rest through
// (a read, a pause, a stop, a save, a delete: refusing those broke the reconnect after a wake). `music.refresh` spends one of the month's 30 flashapi requests. Every command is decided here: the Record makes a new command a type error
// until someone says which it is.
export type SleepClass = "held" | "free";

export const SLEEP_CLASS: Record<CommandType, SleepClass> = {
  "settings.setApiKey": "free",
  "settings.clearApiKey": "free",
  "settings.setMusicKey": "free",
  "settings.clearMusicKey": "free",
  "avatars.pickImportPhoto": "free",
  "media.pickImport": "free",
  "videos.reveal": "free",
  "settings.setExportPath": "free",
  "settings.exportDisplay": "free",
  "videos.revealFolder": "free",
  "stickers.bytes": "free",
  "media.stickerBytes": "free",
  "avatars.delete": "free",
  "settings.get": "free",
  "settings.setBudget": "free",
  "settings.setLibraryPath": "free",
  "settings.setModels": "free",
  "settings.imageModels": "free",
  "settings.setCameraRealism": "free",
  "settings.setConcurrency": "free",
  "settings.setImageAgeCheck": "free",
  "money.status": "free",
  "money.reconcile": "free",
  "avatars.list": "free",
  "avatars.estimate": "free",
  "avatars.estimateCandidates": "free",
  "avatars.estimateRewriteDescriptor": "free",
  "avatars.createDraft": "held",
  "avatars.generateCandidates": "held",
  "avatars.cancel": "free",
  "avatars.pick": "free",
  "avatars.archive": "free",
  "avatars.editDescriptor": "free",
  "avatars.estimateCheckDescriptor": "free",
  "avatars.checkDescriptor": "held",
  "avatars.deletePreview": "free",
  "avatars.rewriteDescriptor": "held",
  "avatars.estimateImport": "free",
  "avatars.importAvatar": "held",
  "runs.estimate": "free",
  "runs.start": "held",
  "runs.estimateFromScenes": "free",
  "runs.startFromScenes": "held",
  "runs.estimateImages": "free",
  "runs.cancel": "free",
  "runs.estimateResume": "free",
  "runs.resume": "held",
  "runs.list": "free",
  "photos.list": "free",
  "photos.setRejected": "free",
  "videos.render": "free",
  "videos.cancel": "free",
  "videos.list": "free",
  "videos.delete": "free",
  "videos.get": "free",
  "videos.quarantineRecords": "free",
  "photos.rebuildRejected": "free",
  "music.status": "free",
  "music.refresh": "held",
  "music.recoverQuotaLog": "free",
  "music.list": "free",
  "music.peaks": "free",
  "montages.create": "free",
  "montages.get": "free",
  "montages.list": "free",
  "montages.save": "free",
  "montages.delete": "free",
  "montages.focus": "free",
  "montages.textPreview": "free",
  "media.list": "free",
  "media.delete": "free",
  "media.cancelImport": "free",
  "categories.list": "free",
  "categories.estimate": "free",
  "categories.create": "held",
  "categories.regenerate": "held",
  "categories.update": "free",
  "categories.delete": "free",
  "categories.dismissInterrupted": "free",
  "scenes.estimateCompose": "free",
  "scenes.compose": "held",
  "scenes.get": "free",
  "scenes.edit": "free",
  "scenes.estimateWrite": "free",
  "scenes.write": "held",
  "scenes.cancel": "free",
  "scenes.discard": "free",
  "export.check": "free",
  "autopilot.estimate": "free",
  "autopilot.start": "held",
  "autopilot.pause": "free",
  "autopilot.resume": "held",
  "autopilot.stop": "free",
  "autopilot.continueAfterReview": "held",
  "autopilot.list": "free",
  "autopilot.get": "free",
  "autopilot.removeUnreadable": "free",
  "videos.setPublished": "free",
  "media.setForAutopilot": "free",
  "engine.snapshot": "free",
  "engine.events": "free",
};

/** Whether the command waits while the Mac sleeps. */
export function heldWhileAsleep(type: CommandType): boolean {
  return SLEEP_CLASS[type] === "held";
}
