// The built-in sticker set, as the UI (3d.5's sticker panel) and Stage 4 see it.
//
// This file is the authored truth for what exists: ids, Russian names,
// categories, tags, and each sticker's pixel size and loop length. The pictures
// are generated by `studio/scripts/stickers/generateStickers.ts`, which reads
// this manifest, and `studio/assets/stickers/catalog.json` records what it
// produced (file, bytes, sha256). A test fails if the two disagree.
//
// Every loop is authored at 30 fps with one frame per 1/30 s, so `loopFrames`
// is also the loop period in 30 fps frames that the render's in-graph loop and
// the preview's `(t - startMs) mod loop` both use (3b.6, 3d.4).

export type StickerCategoryId = "love" | "sparkle" | "mood" | "nature" | "party" | "abstract" | "pointer";

export interface StickerCategory {
  readonly id: StickerCategoryId;
  readonly nameRu: string;
}

export interface StickerManifestEntry {
  readonly id: string;
  readonly nameRu: string;
  readonly category: StickerCategoryId;
  /** Lower-case English keywords, for search and for Stage 4's choice of sticker. */
  readonly tags: readonly string[];
  /** Width and height in pixels; every built-in sticker is square. */
  readonly size: number;
  /** The loop length in 30 fps frames. */
  readonly loopFrames: number;
  /** The frame index a thumbnail should show, when frame 0 is not representative (a flash). Defaults to 0. */
  readonly posterFrame?: number;
}

/** The contract's `Id` (studio/shared/engine/primitives.ts), so a sticker id also passes the spec's zod schema. */
export const STICKER_ID_PATTERN = /^[a-z0-9-]{8,64}$/;

/** Every built-in sticker is authored at this square size, upscaled by the render to its box (at most 0.6 of the frame width, 648 px). */
export const BUILTIN_STICKER_SIZE = 320;

export const STICKER_CATEGORIES: readonly StickerCategory[] = [
  { id: "love", nameRu: "Любовь" },
  { id: "sparkle", nameRu: "Блеск" },
  { id: "mood", nameRu: "Эмоции" },
  { id: "nature", nameRu: "Природа" },
  { id: "party", nameRu: "Праздник" },
  { id: "abstract", nameRu: "Абстракция" },
  { id: "pointer", nameRu: "Указатели" },
];

export const STICKER_MANIFEST: readonly StickerManifestEntry[] = [
  { id: "heart-pulse", nameRu: "Сердце", category: "love", tags: ["heart", "love", "pulse", "romance"], size: BUILTIN_STICKER_SIZE, loopFrames: 24 },
  { id: "sparkle-twinkle", nameRu: "Искры", category: "sparkle", tags: ["sparkle", "twinkle", "shine", "magic"], size: BUILTIN_STICKER_SIZE, loopFrames: 30 },
  { id: "star-spin", nameRu: "Звезда", category: "sparkle", tags: ["star", "spin", "gold", "award"], size: BUILTIN_STICKER_SIZE, loopFrames: 36 },
  { id: "fire-flicker", nameRu: "Огонь", category: "mood", tags: ["fire", "flame", "hot", "trend"], size: BUILTIN_STICKER_SIZE, loopFrames: 24 },
  { id: "lightning-flash", nameRu: "Молния", category: "mood", tags: ["lightning", "bolt", "energy", "shock"], size: BUILTIN_STICKER_SIZE, loopFrames: 24, posterFrame: 6 },
  { id: "bubble-float", nameRu: "Пузыри", category: "nature", tags: ["bubbles", "float", "water", "calm"], size: BUILTIN_STICKER_SIZE, loopFrames: 48 },
  { id: "sun-rays", nameRu: "Солнце", category: "nature", tags: ["sun", "rays", "summer", "warm"], size: BUILTIN_STICKER_SIZE, loopFrames: 30 },
  { id: "confetti-fall", nameRu: "Конфетти", category: "party", tags: ["confetti", "party", "celebrate", "birthday"], size: BUILTIN_STICKER_SIZE, loopFrames: 48 },
  { id: "ripple-rings", nameRu: "Волны", category: "abstract", tags: ["ripple", "rings", "wave", "pulse"], size: BUILTIN_STICKER_SIZE, loopFrames: 36 },
  { id: "arrow-bounce", nameRu: "Стрелка", category: "pointer", tags: ["arrow", "down", "bounce", "look"], size: BUILTIN_STICKER_SIZE, loopFrames: 24 },
];

const BY_ID: ReadonlyMap<string, StickerManifestEntry> = new Map(STICKER_MANIFEST.map((s) => [s.id, s]));

/** The manifest entry for `id`, or undefined. Never matches an inherited property name. */
export function stickerById(id: string): StickerManifestEntry | undefined {
  return BY_ID.get(id);
}
